### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by nschetter** [nschetter/water_safety_tracker#1]
reports

| id | location | surroundings | plant_treatment | comments | source_id | group_id |
| --- | --: | --: | --: | --: | --: | --: |
| 1 | Toledo, Ohio | traces of litter | litter clean-up | none | 1 | 1 |
| 2 | Holland, Ohio | appears  clean | none | no test kit | 2 | 2 |
| 3 | Luna Pier, Michigan | water looks green | chlorinate | high in phosphates | 3 | 3 |
| 4 | Chicago, Illinois | nearby foundry | watershed protection | plant dumping metals | 4 | 4 |
| 5 | Munich, Germany | sewage drain at mouth | ultraviolet light | none | 5 | 5 |

sources

| id | name |
| --- | --: |
| 1 | Maumee River |
| 2 | Swan Creek |
| 3 | Lake Erie |
| 4 | Lake Michigan |
| 5 | Isar River |

groups

| id | name |
| --- | --: |
| 1 | Mr. Smith's class |
| 2 | Enviro. Club |
| 3 | Ohio Environmental Academy |
| 4 | Wildwood Academy |
| 5 | Frau Blatt's 4th grade class |

pollutants

| id | name |
| --- | --: |
| 1 | none |
| 2 | plastic litter |
| 3 | high phosphate levels |
| 4 | arsenic |
| 5 | raw sewage |

pollutant_reports

| report_id | pollutant_id |
| --- | --: |
| 1 | 2 |
| 2 | 1 |
| 3 | 3 |
| 4 | 4 |
| 5 | 5 |

**Comment by sumeetjain** [comment]
Location doesn't appear to be used anywhere.

Can you add at least 3 more rows to each table please? I think there's a disconnect between our understandings – and maybe even with your own understanding of the project. I think more sample data will help move the conversation forward.
